// html-render.mjs — self-contained HTML projections for `samemind board --html` and
// `samemind handoff --html` (see gbrain idea-html-projections.md: canon stays markdown,
// HTML is always a generated face, never storage).
//
// This module is a PURE RENDERER: it consumes the same data models board.mjs/handoff.mjs
// already build for the markdown output (`buildBoardModel` / `buildHandoffModel`) — it does
// not re-derive filtering/sorting logic, and it never parses the markdown the other renderer
// produces. One data model, two faces (markdown + HTML).
//
// Hard constraints (see gbrain idea + the naряд that wired this in):
//   - zero external resources — no CDN, no <link>, no remote fonts/images/scripts
//   - zero JavaScript — this is a static report, not an app
//   - light + dark theme via `prefers-color-scheme` (no toggle, no JS)
//   - mobile-friendly: max-width layout, wrapping long titles/paths
//   - a small SVG visualization per page (board: kanban bar chart + Ideas strip;
//     handoff: decision timeline), generated by code, not a charting library
import { pathToId } from './okf.mjs';
import { titleOf, linkOf, oneline, statusOf, dateOf, ageDays, AGING_THRESHOLD_DAYS, normProj, firstRelPath } from '../board.mjs';
import { cite, oneLine, docDate, extractSection, firstBullets } from '../handoff.mjs';

/** Escape a string for safe interpolation into HTML text/attribute content. */
export function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// ─────────────────────────────── page shell (CSS, no JS) ───────────────────────────────

const STYLE = `
:root{
  --bg:#ffffff; --fg:#1a1d21; --muted:#5f6672; --border:#e2e4e8; --card-bg:#f6f7f9;
  --code-bg:#eef0f3; --link:#2657c2;
  --c-backlog:#64748b; --c-inprogress:#2563eb; --c-blocked:#dc2626; --c-done:#16a34a;
  --c-plan:#7c3aed; --c-spark:#b45309; --c-incubating:#c2410c; --c-adopted:#16a34a;
  --c-axis:#c7cbd3; --c-dot:#2563eb;
}
@media (prefers-color-scheme: dark){
  :root{
    --bg:#15171b; --fg:#e6e8eb; --muted:#9aa1ac; --border:#2b2e34; --card-bg:#1c1f24;
    --code-bg:#23262c; --link:#7aa2ff;
    --c-backlog:#94a3b8; --c-inprogress:#60a5fa; --c-blocked:#f87171; --c-done:#4ade80;
    --c-plan:#a78bfa; --c-spark:#facc15; --c-incubating:#fb923c; --c-adopted:#4ade80;
    --c-axis:#3a3e46; --c-dot:#60a5fa;
  }
}
*{box-sizing:border-box;}
html,body{margin:0;padding:0;}
body{
  background:var(--bg); color:var(--fg);
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  line-height:1.55; max-width:860px; margin:0 auto; padding:28px 18px 72px;
  overflow-wrap:anywhere;
}
h1{font-size:1.6rem; margin:0 0 4px;}
h2{font-size:1.15rem; margin:34px 0 10px; border-bottom:1px solid var(--border); padding-bottom:6px;}
h3{font-size:1rem; margin:18px 0 6px;}
p{margin:6px 0;}
.muted{color:var(--muted); font-size:0.9rem;}
.count{color:var(--muted); font-weight:400; font-size:0.85em;}
code, .cite{
  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:0.85em;
  background:var(--code-bg); border-radius:4px; padding:1px 5px; color:var(--muted);
}
.cards{display:flex; flex-direction:column; gap:10px;}
.card{
  border:1px solid var(--border); background:var(--card-bg); border-radius:10px;
  padding:10px 14px;
}
.card-head{display:flex; flex-wrap:wrap; align-items:baseline; gap:8px;}
.card-title{font-weight:600;}
.desc{color:var(--muted); font-size:0.92em; margin-top:3px;}
.reason{color:var(--c-blocked); font-size:0.9em; margin-top:4px;}
.age{color:var(--muted); font-size:0.85em; margin-top:2px;}
.age .aging{color:var(--c-blocked); font-weight:600;}
.badge{
  display:inline-block; font-size:0.72rem; font-weight:600; text-transform:uppercase;
  letter-spacing:0.02em; border-radius:999px; padding:2px 9px; color:#fff;
}
.badge-backlog{background:var(--c-backlog);}
.badge-inprogress{background:var(--c-inprogress);}
.badge-blocked{background:var(--c-blocked);}
.badge-done{background:var(--c-done);}
.badge-plan{background:var(--c-plan);}
.empty{color:var(--muted); font-style:italic; font-size:0.92em;}
.viz-block{margin:10px 0 18px;}
.chart-svg{width:100%; height:auto; display:block;}
svg text{fill:var(--fg);}
.svg-label{font-size:12px;}
.svg-count{font-size:12px; fill:var(--muted);}
.svg-bar-backlog{fill:var(--c-backlog);}
.svg-bar-inprogress{fill:var(--c-inprogress);}
.svg-bar-blocked{fill:var(--c-blocked);}
.svg-bar-done{fill:var(--c-done);}
.svg-strip-spark{fill:var(--c-spark);}
.svg-strip-incubating{fill:var(--c-incubating);}
.svg-strip-adopted{fill:var(--c-adopted);}
.svg-strip-empty{fill:var(--border);}
.svg-axis{stroke:var(--c-axis); stroke-width:2;}
.svg-dot{fill:var(--c-dot);}
.svg-dot-label{font-size:11px; fill:var(--muted);}
.legend{font-size:0.82rem; color:var(--muted); margin-top:4px;}
.legend-item{margin-right:14px; display:inline-flex; align-items:center; white-space:nowrap;}
.legend-item i{display:inline-block; width:9px; height:9px; border-radius:2px; margin-right:5px;}
.legend-spark i{background:var(--c-spark);}
.legend-incubating i{background:var(--c-incubating);}
.legend-adopted i{background:var(--c-adopted);}
.open-list{padding-left:20px;}
.open-list li{margin:4px 0;}
.arrow{color:var(--muted);}
footer{margin-top:40px; color:var(--muted); font-size:0.78rem; border-top:1px solid var(--border); padding-top:10px;}
@media (max-width:600px){
  body{padding:18px 12px 56px;}
  h1{font-size:1.35rem;}
  .card-head{gap:6px;}
}
`;

function pageShell({ title, bodyHtml, generatedAt }) {
  return `<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>${STYLE}</style>
</head>
<body>
${bodyHtml}
<footer>samemind — generated ${esc(generatedAt)}. Canon stays markdown; this page is a generated face, never storage.</footer>
</body>
</html>
`;
}

function emptyNote(text = 'пусто') {
  return `<p class="empty">${esc(text)}</p>`;
}

// ─────────────────────────────────────── SVG bits ───────────────────────────────────────

/** Horizontal bar chart over `[{label, value, cls}]` — the four kanban column counts. */
export function svgKanbanBars(counts) {
  const barH = 22;
  const gapY = 10;
  const labelW = 108;
  const maxBarW = 220;
  const padTop = 10;
  const padRight = 46;
  const max = Math.max(1, ...counts.map(c => c.value));
  const width = labelW + maxBarW + padRight;
  const height = padTop + counts.length * (barH + gapY);

  const rows = counts.map((c, i) => {
    const y = padTop + i * (barH + gapY);
    const cy = y + barH / 2 + 4;
    const w = c.value === 0 ? 0 : Math.max(6, Math.round((c.value / max) * maxBarW));
    const bar = c.value === 0
      ? `<rect x="${labelW}" y="${y}" width="2" height="${barH}" rx="1" class="svg-bar-${c.cls}"></rect>`
      : `<rect x="${labelW}" y="${y}" width="${w}" height="${barH}" rx="4" class="svg-bar-${c.cls}"></rect>`;
    return `<text x="0" y="${cy}" class="svg-label">${esc(c.label)}</text>${bar}<text x="${labelW + Math.max(w, 2) + 8}" y="${cy}" class="svg-count">${c.value}</text>`;
  }).join('');

  const alt = counts.map(c => `${c.label} ${c.value}`).join(', ');
  return `<svg viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" class="chart-svg" role="img" aria-label="Kanban columns: ${esc(alt)}">${rows}</svg>`;
}

/** Stacked horizontal strip over `[{label, value, cls}]` — Ideas by status, plus a text legend. */
export function svgIdeasStrip(segments) {
  const width = 360;
  const height = 24;
  const total = segments.reduce((s, x) => s + x.value, 0);

  let x = 0;
  let rects = '';
  if (total === 0) {
    rects = `<rect x="0" y="0" width="${width}" height="${height}" rx="4" class="svg-strip-empty"></rect>`;
  } else {
    for (const seg of segments) {
      if (seg.value <= 0) continue;
      const w = Math.max(3, Math.round((seg.value / total) * width));
      rects += `<rect x="${x}" y="0" width="${w}" height="${height}" class="svg-strip-${seg.cls}"><title>${esc(seg.label)}: ${seg.value}</title></rect>`;
      x += w;
    }
  }
  const alt = segments.map(s => `${s.label} ${s.value}`).join(', ');
  const svg = `<svg viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" class="chart-svg" role="img" aria-label="Ideas by status: ${esc(alt)}">${rects}</svg>`;
  const legend = `<div class="legend">${segments.map(s => `<span class="legend-item legend-${s.cls}"><i></i>${esc(s.label)} ${s.value}</span>`).join('')}</div>`;
  return svg + legend;
}

/** Left-to-right dot timeline over `[{label, date}]` (oldest first) — recent decisions. */
export function svgDecisionTimeline(points) {
  const height = 66;
  const y = 32;
  if (!points.length) {
    return `<svg viewBox="0 0 320 ${height}" width="320" height="${height}" class="chart-svg" role="img" aria-label="No recent decisions"><line x1="20" y1="${y}" x2="300" y2="${y}" class="svg-axis"/></svg>`;
  }
  const n = points.length;
  const width = Math.max(320, 74 * n);
  const x0 = 26;
  const x1 = width - 26;
  let dots = '';
  points.forEach((p, i) => {
    const x = n === 1 ? (x0 + x1) / 2 : x0 + (i * (x1 - x0)) / (n - 1);
    dots += `<circle cx="${x}" cy="${y}" r="5" class="svg-dot"><title>${esc(p.date || '?')} — ${esc(p.label)}</title></circle>`;
    dots += `<text x="${x}" y="${y - 12}" text-anchor="middle" class="svg-dot-label">${esc(p.date || '?')}</text>`;
  });
  const alt = points.map(p => `${p.date || '?'} ${p.label}`).join(', ');
  return `<svg viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" class="chart-svg" role="img" aria-label="Decision timeline: ${esc(alt)}"><line x1="${x0}" y1="${y}" x2="${x1}" y2="${y}" class="svg-axis"/>${dots}</svg>`;
}

// ───────────────────────────────────── board → HTML ─────────────────────────────────────

function taskCard(d, nowMs, badgeCls, badgeLabel) {
  const parts = [`<div class="card-head"><span class="badge badge-${badgeCls}">${esc(badgeLabel)}</span><span class="card-title">${esc(titleOf(d))}</span><span class="cite">${esc(linkOf(d))}</span></div>`];
  const desc = oneline(d);
  if (desc) parts.push(`<div class="desc">${esc(desc)}</div>`);
  if (statusOf(d) === 'blocked') {
    const reason = String(d.fm?.blocked_reason || '').trim();
    if (reason) parts.push(`<div class="reason">⛔ ${esc(reason)}</div>`);
    const age = ageDays(d, nowMs);
    if (Number.isFinite(age) && age >= 0) {
      const aging = age >= AGING_THRESHOLD_DAYS ? ' <span class="aging">(aging)</span>' : '';
      parts.push(`<div class="age">⏳ ${age}d${aging}</div>`);
    }
  }
  return `<div class="card">${parts.join('')}</div>`;
}

/** Event-ledger 🔥 Open failures card (docs/event-ledger.md) — reuses the blocked (red) badge. */
function openFailureCard(f) {
  const when = esc(String(f.ts || '').slice(0, 16).replace('T', ' '));
  const artifact = f.artifact ? `<div class="desc"><code>${esc(f.artifact)}</code></div>` : '';
  return `<div class="card"><div class="card-head"><span class="badge badge-blocked">${esc(f.phase)}/${esc(f.status)}</span><span class="card-title">${esc(f.topic)}</span><span class="cite">${esc(f.actor)}, ${when}</span></div><div class="desc">${esc(f.action)}</div>${artifact}</div>`;
}

function planCard(d) {
  const desc = oneline(d);
  return `<div class="card"><div class="card-head"><span class="badge badge-plan">${esc(statusOf(d) || '?')}</span><span class="card-title">${esc(titleOf(d))}</span><span class="cite">${esc(linkOf(d))}</span></div>${desc ? `<div class="desc">${esc(desc)}</div>` : ''}</div>`;
}

function ideaCard(d) {
  const desc = oneline(d);
  return `<div class="card"><div class="card-head"><span class="card-title">${esc(titleOf(d))}</span><span class="cite">${esc(linkOf(d))}</span></div>${desc ? `<div class="desc">${esc(desc)}</div>` : ''}</div>`;
}

function adoptedIdeaLine(d, byId) {
  const target = firstRelPath(d, 'led_to');
  let arrow = '';
  if (target) {
    const plan = byId.get(pathToId(target));
    arrow = plan
      ? ` <span class="arrow">&rarr;</span> ${esc(titleOf(plan))} <span class="cite">${esc(linkOf(plan))}</span>`
      : ` <span class="arrow">&rarr;</span> <span class="cite">${esc(target)}</span>`;
  }
  return `<li>${esc(titleOf(d))}${arrow}</li>`;
}

function recentCard(d) {
  const t = String(d.fm?.type || '').trim() || '—';
  const desc = oneline(d);
  return `<div class="card"><div class="card-head"><span class="badge badge-plan">${esc(t)}</span><span class="card-title">${esc(titleOf(d))}</span><span class="cite">${esc(linkOf(d))}</span></div>${desc ? `<div class="desc">${esc(desc)}</div>` : ''}</div>`;
}

function sessionCard(d) {
  const date = dateOf(d);
  const desc = oneline(d);
  return `<div class="card"><div class="card-head"><span class="card-title">${esc(titleOf(d))}</span>${date ? `<span class="muted">${esc(date)}</span>` : ''}<span class="cite">${esc(linkOf(d))}</span></div>${desc ? `<div class="desc">${esc(desc)}</div>` : ''}</div>`;
}

function cardsOrEmpty(items, renderer) {
  if (!items.length) return emptyNote();
  return `<div class="cards">${items.map(renderer).join('')}</div>`;
}

/**
 * Render the board data model (tools/board.mjs `buildBoardModel`) as a self-contained
 * HTML page: inline CSS, no CDN/JS, light+dark via prefers-color-scheme.
 */
export function renderBoardHtml(model) {
  const {
    nowMs, doneLimit, recentDays, project,
    backlog, inprog, blocked, done, plans,
    ideaIncubating, ideaSpark, ideaAdopted, ideasVisible, byId,
    recent, sessions,
    openFailuresShown, openFailuresTotal,
  } = model;

  const kanbanSvg = svgKanbanBars([
    { label: 'Backlog', value: backlog.length, cls: 'backlog' },
    { label: 'In progress', value: inprog.length, cls: 'inprogress' },
    { label: 'Blocked', value: blocked.length, cls: 'blocked' },
    { label: `Done · last ${doneLimit}`, value: done.length, cls: 'done' },
  ]);

  const ideasSvg = svgIdeasStrip([
    { label: 'Spark', value: ideaSpark.length, cls: 'spark' },
    { label: 'Incubating', value: ideaIncubating.length, cls: 'incubating' },
    { label: 'Adopted', value: ideaAdopted.length, cls: 'adopted' },
  ]);

  const generatedAt = new Date(nowMs).toISOString();

  let body = '';
  body += `<h1>Dashboard</h1>`;
  body += `<p class="muted">Memory kanban — what's in progress, what's done, what's stuck.</p>`;
  if (project) body += `<p class="muted">Task filter: project <code>${esc(normProj(project))}</code> (Plans / Ideas / Recent / Sessions — bundle-wide).</p>`;

  body += `<div class="viz-block">${kanbanSvg}</div>`;

  const openFailuresNote = openFailuresTotal > (openFailuresShown?.length || 0)
    ? `<p class="muted">…and ${openFailuresTotal - openFailuresShown.length} more — <code>samemind ledger status</code></p>`
    : '';
  body += `<h2>🔥 Open failures <span class="count">(${openFailuresTotal})</span></h2>${cardsOrEmpty(openFailuresShown || [], openFailureCard)}${openFailuresNote}`;

  body += `<h2>🆕 Backlog <span class="count">(${backlog.length})</span></h2>${cardsOrEmpty(backlog, d => taskCard(d, nowMs, 'backlog', 'backlog'))}`;
  body += `<h2>🔧 In progress <span class="count">(${inprog.length})</span></h2>${cardsOrEmpty(inprog, d => taskCard(d, nowMs, 'inprogress', 'in progress'))}`;
  body += `<h2>🔴 Blocked <span class="count">(${blocked.length})</span></h2>${cardsOrEmpty(blocked, d => taskCard(d, nowMs, 'blocked', 'blocked'))}`;
  body += `<h2>✅ Done · last ${doneLimit} <span class="count">(${done.length})</span></h2>${cardsOrEmpty(done, d => taskCard(d, nowMs, 'done', 'done'))}`;
  body += `<h2>📋 Plans <span class="count">(${plans.length})</span></h2>${cardsOrEmpty(plans, planCard)}`;

  body += `<h2>💡 Ideas <span class="count">(${ideasVisible.length})</span></h2>`;
  body += `<div class="viz-block">${ideasSvg}</div>`;
  body += cardsOrEmpty(ideasVisible, ideaCard);
  if (ideaAdopted.length) {
    body += `<h3>Adopted &rarr; Plans <span class="count">(${ideaAdopted.length})</span></h3>`;
    body += `<ul>${ideaAdopted.map(d => adoptedIdeaLine(d, byId)).join('')}</ul>`;
  }

  body += `<h2>🕒 Recent <span class="count">(last ${recentDays}d, ${recent.length})</span></h2>${cardsOrEmpty(recent, recentCard)}`;
  body += `<h3>Recent sessions <span class="count">(${sessions.length})</span></h3>${cardsOrEmpty(sessions, sessionCard)}`;

  return pageShell({ title: 'Dashboard — samemind board', bodyHtml: body, generatedAt });
}

// ──────────────────────────────────── handoff → HTML ────────────────────────────────────

function activeCard(d) {
  const st = statusOf(d);
  const title = esc(oneLine(d.fm.title || d.id, 90));
  const path = esc(cite(d));
  if (st === 'blocked') {
    const reason = esc(oneLine(d.fm.blocked_reason || '(no reason)', 120));
    return `<div class="card"><div class="card-head"><span class="badge badge-blocked">blocked</span><span class="card-title">${title}</span><span class="cite">${path}</span></div><div class="reason">⛔ ${reason}</div></div>`;
  }
  return `<div class="card"><div class="card-head"><span class="badge badge-inprogress">in progress</span><span class="card-title">${title}</span><span class="cite">${path}</span></div></div>`;
}

function decisionCard({ d, date }) {
  const title = esc(oneLine(d.fm.title || d.fm.description || d.id, 100));
  const when = esc(date || '?');
  return `<div class="card"><div class="card-head"><span class="muted">${when}</span><span class="card-title">${title}</span><span class="cite">${esc(cite(d))}</span></div></div>`;
}

function planInForceCard(d) {
  const title = esc(oneLine(d.fm.title || d.id, 90));
  return `<div class="card"><div class="card-head"><span class="badge badge-plan">${esc(statusOf(d))}</span><span class="card-title">${title}</span><span class="cite">${esc(cite(d))}</span></div></div>`;
}

function lastSessionCard(d) {
  const title = esc(oneLine(d.fm.title || d.id, 90));
  const eng = esc(d.fm.engine ? String(d.fm.engine) : '?');
  const when = esc(docDate(d) || '?');
  const doneB = firstBullets(extractSection(d.body, /^done$/i), 2);
  const decidedB = firstBullets(extractSection(d.body, /^decided$/i), 2);
  const nextB = firstBullets(extractSection(d.body, /^next$/i), 2);
  let extra = '';
  if (doneB.length) extra += `<div class="desc">Done: ${esc(oneLine(doneB.join(' · '), 160))}</div>`;
  if (decidedB.length) extra += `<div class="desc">Decided: ${esc(oneLine(decidedB.join(' · '), 160))}</div>`;
  if (nextB.length) extra += `<div class="desc">Next: ${esc(oneLine(nextB.join(' · '), 160))}</div>`;
  if (!doneB.length && !decidedB.length && !nextB.length) extra = `<div class="desc">${emptyNote('see ' + cite(d))}</div>`;
  return `<div class="card"><div class="card-head"><span class="card-title">${title}</span><span class="muted">${eng}, ${when}</span><span class="cite">${esc(cite(d))}</span></div>${extra}</div>`;
}

/**
 * Render the handoff data model (tools/handoff.mjs `buildHandoffModel`) as a self-contained
 * HTML page: inline CSS, no CDN/JS, light+dark via prefers-color-scheme.
 */
export function renderHandoffHtml(model) {
  const { projectKey, dayWindow, active, recentDecisions, plansInForce, lastSession, blocked, sessionNext } = model;
  // время — из модели (buildHandoffModel фиксирует его один раз): рендер обязан быть чистой функцией,
  // иначе два вызова на границе миллисекунды дают разные байты (ловилось флаки-тестом)
  const generatedAt = new Date(model.nowMs ?? Date.now()).toISOString();

  // oldest → newest, left to right, for the timeline
  const timelinePoints = [...recentDecisions].reverse().map(({ d, date }) => ({
    label: oneLine(d.fm.title || d.fm.description || d.id, 40),
    date: date || '?',
  }));

  let body = '';
  body += `<h1>Handoff — work state</h1>`;
  body += `<p class="muted">${projectKey ? `project filter: <code>${esc(projectKey)}</code> · ` : ''}last ${dayWindow}d</p>`;

  body += `<h2>Active <span class="count">(${active.length})</span></h2>${cardsOrEmpty(active, activeCard)}`;

  body += `<h2>Last decisions <span class="count">(${dayWindow}d, ${recentDecisions.length})</span></h2>`;
  body += `<div class="viz-block">${svgDecisionTimeline(timelinePoints)}</div>`;
  body += cardsOrEmpty(recentDecisions, decisionCard);

  body += `<h2>Plans in force <span class="count">(${plansInForce.length})</span></h2>${cardsOrEmpty(plansInForce, planInForceCard)}`;

  body += `<h2>Last session</h2>${lastSession ? lastSessionCard(lastSession) : emptyNote()}`;

  body += `<h2>Open questions</h2>`;
  const openItems = [];
  for (const d of blocked) {
    const title = esc(oneLine(d.fm.title || d.id, 80));
    const reason = esc(oneLine(d.fm.blocked_reason || '(no reason)', 100));
    openItems.push(`<li>blocked: ${title} — ${reason} <span class="cite">${esc(cite(d))}</span></li>`);
  }
  for (const n of sessionNext) {
    openItems.push(`<li>next: ${esc(oneLine(n, 140))}</li>`);
  }
  body += openItems.length ? `<ul class="open-list">${openItems.join('')}</ul>` : emptyNote();

  return pageShell({ title: 'Handoff — samemind work state', bodyHtml: body, generatedAt });
}
