#!/usr/bin/env node
// reconcile.mjs — Ф2 bi-temporal supersede: PROPOSES which canon fact should be marked
// `superseded_by` another. Reuses the same same-type/title-tag-Jaccard heuristic as
// tools/consolidate.mjs's "⚔️ Contradictions" section, then resolves *direction* by file mtime
// (the more recently touched file is the presumed replacement).
//
// Human-gate, same spirit as consolidate.mjs/forget.mjs: this tool NEVER writes to a concept's
// frontmatter. It only prints (or, with --write, saves) a markdown report of proposals for a
// human — or a curating agent acting on explicit human instruction — to apply by hand.
//   node tools/reconcile.mjs [--dir <subpath>] [--write]
import { writeFileSync, mkdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ROOT, load } from './lib/okf.mjs';
import { findContradictions, engineOf } from './consolidate.mjs';

const REPORT = join(ROOT, 'inbox', '_reconcile-report.md');

/** mtime (ms) of a doc's file on disk — used only to pick proposal direction. Missing file → 0
 *  (treated as "oldest"), so a synthetic/test doc without a real file never wins the "newer" slot. */
function mtimeOf(doc) {
  try { return statSync(doc.file).mtimeMs; } catch { return 0; }
}

/**
 * Turn consolidate.mjs's symmetric contradiction pairs into directional proposals: "mark the
 * OLDER file (by mtime) superseded_by the NEWER one" — same subject (title/tag overlap ≥
 * threshold), no existing supersedes/superseded_by link between them yet.
 */
export function buildProposals(docs, { dir = null, threshold } = {}) {
  const prefix = dir ? dir.replace(/^\/+|\/+$/g, '') + '/' : null;
  const scoped = prefix ? docs.filter(d => d.id.startsWith(prefix)) : docs;
  const byId = new Map(scoped.map(d => [d.id, d]));
  const pairs = findContradictions(scoped, threshold != null ? { threshold } : {});
  return pairs.map(({ a, b, type, score }) => {
    const da = byId.get(a), db = byId.get(b);
    const [older, newer] = mtimeOf(da) <= mtimeOf(db) ? [da, db] : [db, da];
    return { older: older.id, newer: newer.id, type, score };
  });
}

export function renderReport(proposals) {
  const L = [];
  L.push('# Reconcile proposals — bi-temporal supersede (Ф2)');
  L.push("_Generated by tools/reconcile.mjs. NOT canon — human-gate: proposals only, this tool never writes to any concept's frontmatter._");
  L.push('');
  L.push(`## Proposals: ${proposals.length}`);
  L.push(proposals.length ? '' : '_none_');
  for (const p of proposals) {
    L.push(
      `- предлагаю пометить **${p.older}** \`superseded_by: /${p.newer}.md\`` +
      ` — [${p.type}] same subject as **${p.newer}**, similarity ${p.score.toFixed(2)}, ${p.newer} is newer by mtime`
    );
  }
  L.push('');
  return L.join('\n');
}

function parseArgs(argv = process.argv.slice(2)) {
  const write = argv.includes('--write');
  const di = argv.indexOf('--dir');
  const dir = di >= 0 ? argv[di + 1] : null;
  return { write, dir };
}

function main() {
  const { write, dir } = parseArgs();
  // includeSecret: a contradiction inside the secret tier is still a contradiction; mirror/inbox
  // stay excluded — reconcile targets canon facts, same scope as consolidate.mjs's contradictions
  // section (raw/mirror notes have no supersede lifecycle of their own).
  const docs = load({ includeSecret: true }).filter(d => !d.reserved);
  const canon = docs.filter(d => engineOf(d.id) === 'canon' && d.id.includes('/'));
  const proposals = buildProposals(canon, { dir });
  const out = renderReport(proposals);
  process.stdout.write(out + '\n');
  if (write) {
    mkdirSync(dirname(REPORT), { recursive: true }); // inbox/ may not exist yet on a fresh bundle
    writeFileSync(REPORT, out + '\n');
    console.log(`\n→ written: ${REPORT}`);
  }
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  main();
}
