#!/usr/bin/env node
// reflect.mjs — Ф5 reflection/forgetting cycle: reconcile (supersede proposals) + consolidate
// (dedup/gap map) + heat re-evaluation (cooled facts), fused into ONE markdown proposal report.
//
// Same human-gate as reconcile.mjs/consolidate.mjs: this tool NEVER writes to a concept's
// frontmatter and NEVER hides/deletes anything. It only prints (or, with --write, saves) a
// report for a human — or a curating agent acting on explicit human instruction — to act on by
// hand (with `forget.mjs`, or by hand-editing `supersedes`/`superseded_by`).
//
// Reuses the existing tools rather than re-implementing their logic (see docs/memory-hygiene.md):
//   - reconcile.mjs's buildProposals/renderReport (bi-temporal supersede proposals, Ф2)
//   - consolidate.mjs's buildConsolidationMap (canon/raw gap + contradiction map)
//   - hygiene.mjs's buildHeatIndex/heatScore (Ф5 tiered heat, over tools/lib/ledger.mjs events)
//
//   node tools/reflect.mjs [--write]
// Not wired into cron/launchd — a manual (or human-triggered) run, per naryad Ф5.
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ROOT, load } from './lib/okf.mjs';
import { readEvents } from './lib/ledger.mjs';
import { buildHeatIndex, heatScore, HEAT_WINDOW_DAYS } from './lib/hygiene.mjs';
import { buildProposals } from './reconcile.mjs';
import { buildConsolidationMap, engineOf } from './consolidate.mjs';

const REPORT = join(ROOT, 'inbox', '_reflect-report.md');

/**
 * Canon docs the ledger touched at some point (heatIndex has their id) whose heat has since
 * fully cooled (heatScore === 0 — last touch fell outside HEAT_WINDOW_DAYS). This is the "что
 * остыло в cold" proposal: an FYI for a human to re-check importance/timestamp, or run
 * `samemind forget` if the fact is truly stale — reflect itself only reports, never acts.
 * Docs the ledger never touched at all are NOT listed here (they were never hot to begin with —
 * heatMultiplier is neutral for them, same as before Ф5; listing every untouched doc would just
 * be the whole bundle, not a useful signal).
 */
export function coolingCandidates(canonDocs, heatIndex, now = Date.now()) {
  return canonDocs
    .filter(d => heatIndex.has(d.id) && heatScore(d, heatIndex, now) === 0)
    .map(d => ({
      id: d.id,
      title: d.fm?.title || d.id,
      touches: heatIndex.get(d.id).count,
      lastTs: heatIndex.get(d.id).lastTs,
    }))
    .sort((a, b) => String(b.lastTs).localeCompare(String(a.lastTs)));
}

export function renderReflectReport({ proposals, consolidation, cooling }) {
  const L = [];
  L.push('# Reflect proposals — reconcile + consolidate + heat (Ф5)');
  L.push("_Generated by tools/reflect.mjs. NOT canon — human-gate: proposals only, this tool never writes to any concept's frontmatter and never hides/deletes anything._");
  L.push('');

  L.push(`## 1. Supersede proposals (reconcile): ${proposals.length}`);
  L.push(proposals.length ? '' : '_none_');
  for (const p of proposals) {
    L.push(
      `- предлагаю пометить **${p.older}** \`superseded_by: /${p.newer}.md\`` +
      ` — [${p.type}] same subject as **${p.newer}**, similarity ${p.score.toFixed(2)}, ${p.newer} is newer by mtime`
    );
  }
  L.push('');

  const mergeCount = consolidation.strong.length + consolidation.single.length;
  L.push(`## 2. Merge candidates (consolidate): 🔴 ${consolidation.strong.length} in ≥2 sources · 🟡 ${consolidation.single.length} single-source`);
  L.push(mergeCount ? '' : '_none_');
  for (const r of consolidation.strong) L.push(`- 🔴 **${r.key}** [${r.engines.join(' + ')}] — ${r.title} — предлагаю слить/продвинуть в канон`);
  for (const r of consolidation.single) L.push(`- 🟡 ${r.key} [${r.engines[0]}] — ${r.title}`);
  L.push('');

  L.push(`## 3. Cooled facts (heat, Ф5): ${cooling.length}`);
  L.push(`_Ledger activity seen at least once, none in the last ${HEAT_WINDOW_DAYS}d — candidates to re-check importance/timestamp, or \`samemind forget <id>\` if truly stale. Never hidden, never demoted below their current rank — only no longer boosted._`);
  L.push(cooling.length ? '' : '_none_');
  for (const c of cooling) {
    L.push(`- **${c.id}** — ${c.touches} ledger touch(es), last ${String(c.lastTs).slice(0, 10)} — предлагаю проверить актуальность`);
  }
  L.push('');

  return L.join('\n');
}

async function main() {
  const write = process.argv.includes('--write');
  // One load() covers all three sub-reports (reconcile only needs canon; consolidate needs
  // mirror+inbox too) — a single filesystem read, no duplicate ranking/loading pass.
  const docs = load({ includeSecret: true, includeMirror: true, includeInbox: true }).filter(d => !d.reserved);
  const canon = docs.filter(d => engineOf(d.id) === 'canon' && d.id.includes('/'));

  const proposals = buildProposals(canon);
  const consolidation = await buildConsolidationMap(docs);
  const heatIndex = buildHeatIndex(readEvents(ROOT));
  const cooling = coolingCandidates(canon, heatIndex);

  const out = renderReflectReport({ proposals, consolidation, cooling });
  process.stdout.write(out + '\n');
  if (write) {
    mkdirSync(dirname(REPORT), { recursive: true });
    writeFileSync(REPORT, out + '\n');
    console.log(`\n→ written: ${REPORT}`);
  }
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  main().catch(e => {
    console.error('Error:', e.message);
    process.exit(1);
  });
}
